### ISSUE TITLE
Blurred number image

### ISSUE THREAD

**Issue by sungeunDev** [AlexSmet/SHNumbersScrollAnimatedView#4]
## What did you do?
I have four animations views, because of spacing between numbers. But there are some resolution broken. Compared to your markdown screenshot, mine's looks blurred. 
Don't you think so? But I do not know what is wrong. Here's the screenshot and code.

- screenshot
<img width="500" alt="screenshot_usecase" src="https://user-images.githubusercontent.com/38233885/49915094-442ca380-fed7-11e8-8472-df1d26668f08.png">

> I use this library to get the total number of users from the server and animate them.
> You can see that the resolution is lower when compared to plain text.

- code
``` swift
@IBOutlet weak var animatedView1: NumberScrollAnimatedView!
@IBOutlet weak var animatedView2: NumberScrollAnimatedView!
@IBOutlet weak var animatedView3: NumberScrollAnimatedView!
@IBOutlet weak var animatedView4: NumberScrollAnimatedView!

private func startAnimation(text: String) {
        let animatedViews = [animatedView1, animatedView2, animatedView3, animatedView4]
        for (idx, view) in animatedViews.enumerated() {
            guard let view = view else { return }
            view.backgroundColor = UIColor(red: 234, green: 126, blue: 106)
            view.font = DesignSystemManager.getFont(name: .notoExtraBold, size: .header)
            view.textColor = .white
            view.layer.cornerRadius = 8
            view.clipsToBounds = true
            
            view.animationDuration = 3
            view.scrollingDirectionRule = { (_, _) in return (idx % 2) == 0 ? .down : .up }
            view.text = String(text[text.index(text.startIndex, offsetBy: idx)])
        }
        
        for view in animatedViews {
            DispatchQueue.main.async {
                view?.startAnimation()
            }
        }
    }
```

## What did you expect to happen?
ℹSharp resolution like plain text.

## What happened instead?
ℹThe screen where the numbers appear is slightly blurred.

## Environment
Xcode version: 10.1
Swift version: 3
Platform(s) running Library: iOS - 9.3 ~ 12.0
**macOS version running Xcode: macOS - 10.14.1 **  
  
++ Let me know if I have any missing information.

**Comment by AlexSmet** [comment]
Hi, 

I've defined the problem and going to fix it tomorrow.

**Comment by AlexSmet** [comment]
Fixed
